// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package com.siyi.grpc.lib;

public interface StockServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 股票的名称
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * 股票的名称
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
